#!C:\Users\kevin\OneDrive\Desktop\Lovely's 100 Days Coding Journey March 6 2025 - June 14, 2025\E2E ML Project AWS Sagemaker\aistarters1stMLProject\python.exe
#
# Author: Mike McKerns (mmckerns @caltech and @uqfoundation)
# Copyright (c) 2018-2024 The Uncertainty Quantification Foundation.
# License: 3-clause BSD.  The full license text is available at:
#  - https://github.com/uqfoundation/pox/blob/master/LICENSE

import pox.__main__
from pox.__main__ import *
__doc__ = pox.__main__.__doc__


if __name__=='__main__':
    import sys
    try:
        func = sys.argv[1]
    except: func = None
    if func:
        try:
            exec('print(%s)' % func)
        except:
            print("Error: incorrect syntax '%s'\n" % func)
            exec('print(%s.__doc__)' % func.split('(')[0])
    else: help()


# End of file 
